### PR TITLE
Update DefaultCard.cs

### PR DESCRIPTION
**Pull request by ansonliam**
Change private to public. In order to extend the Default Card and custom format the layout.

### CODE REVIEW

**Review by cbolandK20 — COMMENTED** [review]
totally fine. Thanks to you I think about a general overhaul of this lousy string replacement implementation. Something more like a Interface which can be implemented and configured in the NLog Xml config.
I will build and publish a new release, but first I have to learn a bit about the githiub action to do such things. I you are experienced in such things - any help is appreciated.

**Review by cbolandK20 — APPROVED** [review]
totally fine

**Comment by ansonliam** [comment]
Thanks. If possible, could you please realise a new update to nuget too?

**Comment by ansonliam** [comment]
> Something more like a Interface which can be implemented and configured in the NLog Xml config.

I would like to help but I am not too sure how to do it exactly in C#... If you do not know how to put a release or other functions in github, you can invite me as **collaborators** in github so that I can help.

**Comment by cbolandK20** [comment]
Version 2.0.0 is out on nuget. Let me know if it suits your needs.

**Pull request merged**
